export const HOME = "/home"
export const LANDING = "/"
export const PROFILE = "/profile"
export const VIDEOS = "/videos"
export const COURSES = "/courses"
export const LOGIN = "/login"
export const PASSWORD_FORGET = "/pw-forget"
